export const register = [
    {
        name:"genre",
        type:"radio",
        defaultValue:"H",
        values:["H","F"]
    },
    {
        name:"firstName",
        type:"text",
        defaultValue:"",
        regex:/^[A-z]*$/,
        placeholder:"Prénom"
    },
    {
        name:"lastName",
        type:"text",
        defaultValue:"",
        regex:/^[A-z]*$/,
        placeholder:"Nom"
    },
    {
        name:"mail",
        type:"email",
        defaultValue:"",
        regex:"",
        placeholder:"Mail"
    },
    {
        name:"birthday",
        type:"date",
        defaultValue:"",
        regex:""
    },
    {
        name:"zipCode",
        type:"text",
        defaultValue:"",
        regex:/^[0-9]*$/,
        placeholder:"Code postal"
    },
    {
        name:"city",
        type:"text",
        defaultValue:"",
        regex:/^[A-z]*$/,
        placeholder:"Ville"
    },
]